# Generated by Django 2.1 on 2019-07-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190714_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orderupdate',
            new_name='OUpdate',
        ),
    ]
