# Generated by Django 2.1 on 2019-07-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190720_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OUpdate',
            new_name='order_update',
        ),
    ]
